/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flying_testndk2_jni_TestJni */

#ifndef _Included_com_flying_testndk2_jni_TestJni
#define _Included_com_flying_testndk2_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flying_testndk2_jni_TestJni
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flying_testndk2_jni_TestJni_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     com_flying_testndk2_jni_TestJni
 * Method:    testClassJava
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_flying_testndk2_jni_TestJni_testClassJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
